# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: acec4d28330f768cae20137ad085ac955a98fa502275c9d74cabd2e33b27b12d6f7a7478b6a3fa7d1b75624adfd537e91d4c8ef5f67b76bd58bd30e8e30b3ce3

test:
  secret_key_base: f79921768b37db6c1eb92ef906e98ea7dbe8d3a653d30a4c19d7cefbb77a5a242b7200b01ea9129da9fc832c928dee6cb915e57a4c04dc5e6b9024a401527577

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
